#ifndef GAME_ERROR_H
#define GAME_ERROR_H

typedef enum game_err {
    GMERR_OK,
    GMERR_ASSET_LIST_FAIL,
    GMERR_SCREEN_ALLOC,
    GMERR_SCREEN_CHARS_ALLOC,
    GMERR_SCREEN_CHAR_OUT_OF_BOUNDS,
    GMERR_RESIZE_FAIL,
    GMERR_REFRESH_FAIL,
    GMERR_CLEAR_FAIL,
    GMERR_COLOR_SET_FAIL,
    GMERR_CURSOR_INVISIBLE_FAIL,
    GMERR_NODELAY_FAIL,
    GMERR_WINDOW_INIT_FAIL,
    GMERR_CBREAK_FAIL,
    GMERR_NOECHO_FAIL,
    GMERR_KEYPAD_FAIL,
    GMERR_ASSET_NOT_FOUND,
    GMERR_ASSET_OPEN_FAIL,
    GMERR_ASSET_SEEK_FAIL,
    GMERR_ASSET_LEN_FAIL,
    GMERR_ASSET_ALLOC_FAIL,
    GMERR_ASSET_READ_FAIL,
    GMERR_ASSET_CLOSE_FAIL,
} game_err_t;

const char* game_err_msg(game_err_t code);

#endif /* GAME_ERROR_H */
